/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.jimbovm.bt.orgchart;

import java.io.IOException;
import java.util.List;
import java.util.Optional;
import java.util.logging.Logger;

import com.github.jimbovm.bt.orgchart.parser.Parser;

public final class App {

	private static final int EXIT_SUCCESS = 0;
	private static final int EXIT_FAILURE = 1;

	private static final int FILE_PATH = 0;
	private static final int EMPLOYEE_1 = 1;
	private static final int EMPLOYEE_2 = 2;

	public static String filePath;

	private static String firstEmployeeName;
	private static String secondEmployeeName;

	private static Logger logger = Logger.getGlobal();

	public static String normalizeName(String name) {
		return name.strip().replaceAll("\s+", " ").toLowerCase();
	}

	public static boolean containsName(List<Employee> employees, String name) {
		return employees.stream().anyMatch(employee -> normalizeName(employee.name()) == name);
	}

	public static void argumentsSetup(String[] args) {

		filePath = args[FILE_PATH];

		if (args.length != 3) {
			System.err.println("Wrong number of arguments.");
			System.err.println("Usage: java -jar app.jar [input file] [employee name] [employee name]");
			System.exit(EXIT_FAILURE);
		}

		firstEmployeeName = normalizeName(args[EMPLOYEE_1]);
		secondEmployeeName = normalizeName(args[EMPLOYEE_2]);

		logger.info("Reading file " + filePath);
		logger.info(String.format("Finding shortest path between \"%s\" (\"%s\") and \"%s\" (\"%s\")",
				firstEmployeeName,
				args[EMPLOYEE_1], secondEmployeeName, args[EMPLOYEE_2]));
	}

	public static void checkEmployeesFound(String[] args, Optional<Employee> employee1,
			Optional<Employee> employee2) {
		final var employee1NotFound = employee1.isEmpty();
		final var employee2NotFound = employee2.isEmpty();

		if (employee1NotFound || employee2NotFound) {
			System.err.println(String.format("Employee %s (%s) not found in input file %s",
					firstEmployeeName,
					args[EMPLOYEE_1], filePath));
			System.err.println(String.format("Employee %s (%s) not found in input file %s",
					secondEmployeeName,
					args[EMPLOYEE_2], filePath));
			System.exit(EXIT_FAILURE);
		}
	}

	public static void main(String[] args) throws Exception {

		argumentsSetup(args);

		try {
			List<Employee> employees = Parser.parse(filePath);
			Hierarchy hierarchy = Hierarchy.of(employees);
			PathFinder pathFinder = new PathFinder(hierarchy);

			Optional<Employee> employee1 = employees.stream()
					.filter(employee -> normalizeName(employee.name())
							.equalsIgnoreCase(firstEmployeeName))
					.findFirst();

			Optional<Employee> employee2 = employees.stream()
					.filter(employee -> normalizeName(employee.name())
							.equalsIgnoreCase(secondEmployeeName))
					.findFirst();

			checkEmployeesFound(args, employee1, employee2);

			// if we're here, we have valid input
			pathFinder.findShortestPath(employee1.get(), employee2.get());
			System.out.println(pathFinder.toString());

			System.exit(EXIT_SUCCESS);

		} catch (IOException e) {
			System.err.println(e.getMessage());
			System.exit(EXIT_FAILURE);
		}
	}
}
